name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode_version: [ latest-stable, 14 ]
        arch: [ "arm64-apple-macosx", "x86_64-apple-macosx" ]
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Xcode Select
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: latest-stable

    - name: Build
      run: swift build -v -c release --triple ${{ matrix.arch }}
